from pathlib import Path
from setuptools import setup, find_packages

setup(
    name='RadEval',
    version='0.1.3',
    author='Jean-Benoit Delbrouck, Justin Xu, Xi Zhang',
    maintainer='Xi Zhang, JB Delbrouck',
    url='https://github.com/jbdel/RadEval',
    project_urls={
        'Bug Reports': 'https://github.com/jbdel/RadEval/issues',
        'Source': 'https://github.com/jbdel/RadEval',
        'Documentation': 'https://github.com/jbdel/RadEval/blob/main/README.md',
    },
    license='MIT',
    description='All-in-one metrics for evaluating AI-generated radiology text',
    long_description=Path("README.md").read_text(encoding="utf-8"),
    long_description_content_type="text/markdown",
    classifiers=[
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3 :: Only',
    ],
    keywords=[
        'radiology',
        'evaluation',
        'natural language processing',
        'radiology report',
        'medical NLP',
        'clinical text generation',
        'LLM',
        'bioNLP',
        'chexbert',
        'radgraph',
        'medical AI'
    ],
    python_requires='>=3.11',
    install_requires=[
        'torch>=2.0',
        'torchvision',
        'transformers>=4.40,<5',
        'radgraph',
        'rouge_score',
        'bert-score>=0.3.13',
        'scikit-learn>=1.8.0',
        'numpy<2',
        'medspacy',
        'stanza',
        'pillow',
        'sentencepiece',
        'datasets>=2.19',
        'accelerate>=0.30',
        'pandas',
        'rich',
        'pyyaml',
        'appdirs',
        'huggingface_hub',
    ],
    extras_require={
        'api': [
            'google-genai',
            'openai',
            'tenacity',
        ],
    },
    packages=find_packages(),
    include_package_data=True,
    package_data={
        "RadEval.metrics.SRRBert": ["*.json"],
    },
    zip_safe=False,
)
