"""Regression test: verify refactored output matches pre-refactor snapshot.

The snapshot was generated by tests/generate_regression_snapshot.py on the
old RadEval(do_*=True) API. This test runs the new metrics={} API and
asserts identical output.
"""
import json
import math
import pytest
from pathlib import Path

from radeval import RadEval

FIXTURE_DIR = Path(__file__).parent / "fixtures"
CPU_FIXTURE = FIXTURE_DIR / "expected_scores_cpu.json"
GPU_FIXTURE = FIXTURE_DIR / "expected_scores_gpu.json"

# Import shared samples
import importlib.util
spec = importlib.util.spec_from_file_location(
    "samples", FIXTURE_DIR / "regression_samples.py")
samples = importlib.util.module_from_spec(spec)
spec.loader.exec_module(samples)
REFS, HYPS = samples.REFS, samples.HYPS


@pytest.fixture(scope="module")
def cpu_expected():
    with open(CPU_FIXTURE) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def gpu_expected():
    if not GPU_FIXTURE.exists():
        pytest.skip("GPU snapshot not available")
    with open(GPU_FIXTURE) as f:
        return json.load(f)


def _assert_close(actual, expected, key, rel_tol=1e-4):
    """Assert two values match: floats by tolerance, lists element-wise, else exact."""
    if isinstance(expected, (int, float)):
        assert math.isclose(float(actual), float(expected), rel_tol=rel_tol), \
            f"{key}: {actual} != {expected}"
    elif isinstance(expected, list):
        assert len(actual) == len(expected), f"{key}: length mismatch"
        for i, (a, e) in enumerate(zip(actual, expected)):
            _assert_close(a, e, f"{key}[{i}]", rel_tol=rel_tol)
    elif isinstance(expected, dict):
        for k, v in expected.items():
            assert k in actual, f"{key}.{k} missing"
            _assert_close(actual[k], v, f"{key}.{k}", rel_tol=rel_tol)
    else:
        assert actual == expected, f"{key}: {actual!r} != {expected!r}"


# --- CPU tier (always runs) ---

def test_regression_cpu_default(cpu_expected):
    evaluator = RadEval(metrics=["bleu", "rouge"], show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in cpu_expected["default"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)


def test_regression_cpu_per_sample(cpu_expected):
    evaluator = RadEval(metrics=["bleu", "rouge"],
                        per_sample=True, show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in cpu_expected["per_sample"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)


def test_regression_cpu_detailed(cpu_expected):
    evaluator = RadEval(metrics=["bleu", "rouge"],
                        detailed=True, show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in cpu_expected["detailed"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)


# --- GPU tier (skips on CPU-only machines) ---

_HAS_GPU = False
try:
    import torch
    _HAS_GPU = torch.cuda.is_available()
except ImportError:
    pass


_GPU_METRICS = [
    "bleu", "rouge", "bertscore",
    "radeval_bertscore", "f1chexbert",
    "srrbert", "ratescore",
    "temporal",
    "radgraph", "radgraph_radcliq", "radcliq",
]


@pytest.mark.skipif(not _HAS_GPU, reason="No GPU available")
@pytest.mark.skipif(not GPU_FIXTURE.exists(), reason="GPU snapshot not generated")
def test_regression_gpu_default(gpu_expected):
    evaluator = RadEval(metrics=_GPU_METRICS, show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in gpu_expected["default"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)


@pytest.mark.skipif(not _HAS_GPU, reason="No GPU available")
@pytest.mark.skipif(not GPU_FIXTURE.exists(), reason="GPU snapshot not generated")
def test_regression_gpu_per_sample(gpu_expected):
    evaluator = RadEval(metrics=_GPU_METRICS, per_sample=True,
                        show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in gpu_expected["per_sample"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)


@pytest.mark.skipif(not _HAS_GPU, reason="No GPU available")
@pytest.mark.skipif(not GPU_FIXTURE.exists(), reason="GPU snapshot not generated")
def test_regression_gpu_detailed(gpu_expected):
    evaluator = RadEval(metrics=_GPU_METRICS, detailed=True,
                        show_progress=False)
    actual = evaluator(refs=REFS, hyps=HYPS)
    for key, exp_val in gpu_expected["detailed"].items():
        assert key in actual, f"Missing key: {key}"
        _assert_close(actual[key], exp_val, key)
