name: libra
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - scikit-learn=1.2.2
  - tqdm
  - pydicom
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - transformers==4.43.3
      - tokenizers>=0.14.0,<0.20
      - sentencepiece==0.1.99
      - shortuuid
      - accelerate==0.33.0
      - peft==0.4.0
      - bitsandbytes==0.41.0
      - pydantic<2,>=1
      - markdown2[all]
      - gradio==3.35.2
      - gradio_client==0.2.9
      - requests
      - httpx==0.24.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - timm==0.6.13